#!/usr/bin/env bash
# One-command installer for a site's on-premise machine.
#
#   curl -fsSL https://camera.schoolsai.work/install.sh | bash
#
# Does everything Phase 1 of docs/PLAN.md used to require by hand: clones
# the repo, installs cloudflared + go2rtc, uses a short-lived install token
# generated by the logged-in dashboard, registers the site/camera with the
# correct account (no customer session key or manual Turso access), writes
# local config, and installs the always-on service. The backend provisions
# one Named Tunnel + one hostname for the site and returns its connector
# token; customers never need a Cloudflare account or Cloudflare Access.
set -euo pipefail

REPO_URL="${CAMERAAIWORK_REPO:-https://github.com/nhannguyenalien/cameraaiwork.git}"
INSTALL_DIR="${CAMERAAIWORK_DIR:-$HOME/cameraaiwork}"
API_BASE="${CAMERAAIWORK_API:-https://camera.schoolsai.work}"
BUNDLE_URL="${CAMERAAIWORK_BUNDLE_URL:-$API_BASE/cameraaiwork-relay.tar.gz}"
INSTALL_TOKEN="${CAMERAAIWORK_INSTALL_TOKEN:-}"

echo "=== cameraaiwork — cài đặt on-site ==="
echo "Sẽ cài vào: $INSTALL_DIR"
echo "Backend: $API_BASE"
echo

# --- 1. Prerequisites ---
if ! command -v node >/dev/null 2>&1; then
  echo "!! Cần cài Node.js trước (https://nodejs.org), rồi chạy lại script này." >&2
  exit 1
fi
if ! command -v git >/dev/null 2>&1; then
  echo "!! Cần cài git trước." >&2
  exit 1
fi
if ! command -v python3 >/dev/null 2>&1; then
  echo "!! Cần Python 3.10+ và module venv để cài AI worker." >&2
  exit 1
fi

if ! command -v cloudflared >/dev/null 2>&1; then
  echo "==> Cài cloudflared..."
  if [[ "$(uname -s)" == "Darwin" ]]; then
    if command -v brew >/dev/null 2>&1; then
      brew install cloudflared
    else
      echo "!! Cần Homebrew để tự cài cloudflared trên macOS, hoặc cài thủ công: https://github.com/cloudflare/cloudflared/releases" >&2
      exit 1
    fi
  else
    arch="$(uname -m)"
    case "$arch" in
      x86_64) cf_asset="cloudflared-linux-amd64" ;;
      aarch64) cf_asset="cloudflared-linux-arm64" ;;
      *) echo "!! Kiến trúc $arch chưa hỗ trợ tự cài cloudflared, cài thủ công: https://github.com/cloudflare/cloudflared/releases" >&2; exit 1 ;;
    esac
    curl -fsSL "https://github.com/cloudflare/cloudflared/releases/latest/download/$cf_asset" -o /tmp/cloudflared
    chmod +x /tmp/cloudflared
    sudo mv /tmp/cloudflared /usr/local/bin/cloudflared
  fi
fi

# --- 2. Get the code ---
if [ -d "$INSTALL_DIR/.git" ]; then
  echo "==> Cập nhật $INSTALL_DIR..."
  git -C "$INSTALL_DIR" pull --ff-only
else
  echo "==> Tải gói relay từ dashboard về $INSTALL_DIR..."
  bundle_dir="$(mktemp -d)"
  curl -fsSL "$BUNDLE_URL" -o "$bundle_dir/cameraaiwork-relay.tar.gz"
  mkdir -p "$INSTALL_DIR"
  tar -xzf "$bundle_dir/cameraaiwork-relay.tar.gz" -C "$INSTALL_DIR" --strip-components=1
  rm -rf "$bundle_dir"
fi
cd "$INSTALL_DIR"

# --- 3. Ask for install token + camera info ---
echo
if [[ -z "$INSTALL_TOKEN" ]]; then
  read -rsp "Dán mã cài đặt một lần từ Dashboard > Cài đặt: " INSTALL_TOKEN
  echo
fi
read -rp "Tên địa điểm (vd: Nhà chính): " SITE_NAME
read -rp "Tên camera [Camera chính]: " CAMERA_NAME
CAMERA_NAME="${CAMERA_NAME:-Camera chính}"
read -rp "IP camera trong LAN: " CAM_IP
read -rp "Username ONVIF: " CAM_USER
read -rsp "Password ONVIF: " CAM_PASS
echo
read -rp "Cổng ONVIF [2020]: " CAM_ONVIF_PORT
CAM_ONVIF_PORT="${CAM_ONVIF_PORT:-2020}"

# --- 4. Claim token and register site + camera atomically ---
echo
echo "==> Gắn VPS với đúng tài khoản và đăng ký camera..."
CLAIM_BODY=$(SITE_NAME="$SITE_NAME" CAMERA_NAME="$CAMERA_NAME" INSTALL_TOKEN="$INSTALL_TOKEN" node -e '
  process.stdout.write(JSON.stringify({
    token: process.env.INSTALL_TOKEN,
    siteName: process.env.SITE_NAME,
    cameraName: process.env.CAMERA_NAME,
    stream: "cam1"
  }))
')
SITE_RESP=$(curl -fsS -X POST "$API_BASE/api/install/claim" \
  -H "Content-Type: application/json" -d "$CLAIM_BODY")
SITE_ID=$(echo "$SITE_RESP" | node -pe 'JSON.parse(require("fs").readFileSync(0,"utf8")).siteId')
RELAY_SECRET=$(echo "$SITE_RESP" | node -pe 'JSON.parse(require("fs").readFileSync(0,"utf8")).relaySecret')
TUNNEL_TOKEN=$(echo "$SITE_RESP" | node -pe 'JSON.parse(require("fs").readFileSync(0,"utf8")).tunnelToken || ""')
echo "    siteId = $SITE_ID"
echo "    camera 'cam1' đã đăng ký"

# --- 5. Write local config (never committed — see .gitignore) ---
CAM_IP="$CAM_IP" CAM_USER="$CAM_USER" CAM_PASS="$CAM_PASS" CAM_ONVIF_PORT="$CAM_ONVIF_PORT" node <<'NODE'
const fs = require("fs");
const camera = [{
  id: "cam1",
  stream: "cam1",
  onvif: {
    ip: process.env.CAM_IP,
    port: Number(process.env.CAM_ONVIF_PORT),
    username: process.env.CAM_USER,
    password: process.env.CAM_PASS,
  },
}];
fs.writeFileSync("apps/relay/cameras.json", `${JSON.stringify(camera, null, 2)}\n`, { mode: 0o600 });
NODE

cat > apps/relay/.env <<EOF
SITE_ID=$SITE_ID
RELAY_PORT=4000
RELAY_SECRET=$RELAY_SECRET
GO2RTC_URL=http://localhost:1984
PAGES_API_URL=$API_BASE
CLOUDFLARE_TUNNEL_TOKEN=$TUNNEL_TOKEN
EOF

echo "==> Đã ghi apps/relay/cameras.json và apps/relay/.env"

# --- 6. go2rtc + relay deps ---
bash infra/setup.sh
(cd apps/relay && npm install --silent)
python3 -m venv ai/worker/.venv
ai/worker/.venv/bin/pip install --quiet -r ai/worker/requirements.txt

# --- 7. Install as an always-on service ---
NODE_PATH="$(command -v node)"
USER_NAME="$(whoami)"

if [[ "$(uname -s)" == "Darwin" ]]; then
  mkdir -p "$HOME/Library/LaunchAgents"

  for svc in go2rtc relay ai; do
    src="infra/launchd/com.cameraaiwork.$svc.plist"
    dest="$HOME/Library/LaunchAgents/com.cameraaiwork.$svc.plist"
    sed -e "s#REPLACE_WITH_REPO_ROOT#$INSTALL_DIR#g" \
        -e "s#REPLACE_WITH_NODE_PATH#$NODE_PATH#g" \
        "$src" > "$dest"
    launchctl unload "$dest" 2>/dev/null || true
    launchctl load "$dest"
  done
  echo "==> Đã cài 3 launchd service (go2rtc, relay, ai). Logs: /tmp/cameraaiwork-*.log"
else
  for svc in go2rtc relay ai; do
    src="infra/systemd/cameraaiwork-$svc.service"
    dest="/etc/systemd/system/cameraaiwork-$svc.service"
    sed -e "s#REPLACE_WITH_REPO_ROOT#$INSTALL_DIR#g" \
        -e "s#REPLACE_WITH_USER#$USER_NAME#g" \
        "$src" | sudo tee "$dest" > /dev/null
  done
  sudo systemctl daemon-reload
  sudo systemctl enable --now cameraaiwork-go2rtc cameraaiwork-relay cameraaiwork-ai
  echo "==> Đã cài 3 systemd service (go2rtc, relay, ai)."
fi

echo
echo "✅ Xong! Mở $API_BASE và đăng nhập đúng email đã tạo mã cài đặt."
echo "   Camera + live view sẽ xuất hiện trong vòng ~10-15 giây (chờ tunnel lên)."
